{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecretName }}
  labels:
    {{- include "logistics.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/{{ required "secrets.neo4jPassword is required" .Values.secrets.neo4jPassword }}"
  neo4j-password: {{ .Values.secrets.neo4jPassword | quote }}
  rabbitmq-password: {{ required "secrets.rabbitmqPassword is required" .Values.secrets.rabbitmqPassword | quote }}
  rabbitmq-erlang-cookie: {{ required "secrets.rabbitmqErlangCookie is required" .Values.secrets.rabbitmqErlangCookie | quote }}
  jwt-signing-key: {{ required "secrets.jwtSigningKey is required" .Values.secrets.jwtSigningKey | quote }}
{{- end }}
